name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # tous les jours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Pacman graph
        uses: Platane/snk@v3
        with:
          github_user_name: nolongeraregistereduser
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate pacman contribution graph"
          add: "output/*"
